name: CI
on: [push, pull_request]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
        id: go

      - name: Check out source
        uses: actions/checkout@v3

      - name: Install libgit2
        run: chmod +x scripts/install_libgit2.sh

      - name: Vet
        run: make vet

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
